[
  {
    name: "Ennahdha",
    stats: {
      pana: { left: 45, neutral: 20, right: 35 },
      coop: { left: 70, neutral: 20, right: 10 },
      econ: { left: 40, neutral: 20, right: 40 },
      reli: { left: 85, neutral: 10, right: 5 },
      soci: { left: 80, neutral: 15, right: 5 },
      demo: { left: 50, neutral: 20, right: 30 },
      decent: { left: 40, neutral: 30, right: 20 },
    },
    weights: {
      pana: 1.5,
      coop: 1,
      econ: 2,
      reli: 3,
      soci: 3,
      demo: 1,
      decent: 1,
    },
  },
  {
    name: "Parti Destourien Libre (PDL)",
    stats: {
      pana: { left: 35, neutral: 0, right: 65 },
      coop: { left: 25, neutral: 10, right: 65 },
      econ: { left: 45, neutral: 5, right: 40 },
      reli: { left: 10, neutral: 15, right: 75 },
      soci: { left: 70, neutral: 10, right: 20 },
      demo: { left: 10, neutral: 15, right: 75 },
      decent: { left: 15, neutral: 10, right: 75 },
    },
    weights: {
      pana: 3,
      coop: 2,
      econ: 1,
      reli: 3,
      soci: 2,
      demo: 3,
      decent: 2,
    },
  },
  {
    name: "Mouvement Echaâb",
    stats: {
      pana: { left: 70, neutral: 20, right: 10 },
      coop: { left: 25, neutral: 0, right: 65 },
      econ: { left: 65, neutral: 10, right: 15 },
      reli: { left: 10, neutral: 20, right: 70 },
      soci: { left: 70, neutral: 10, right: 20 },
      demo: { left: 15, neutral: 25, right: 60 },
      decent: { left: 20, neutral: 10, right: 70 },
    },
    weights: {
      pana: 3,
      coop: 1,
      econ: 2,
      reli: 3,
      soci: 3,
      demo: 3,
      decent: 1,
    },
  },
  {
    name: "Afek Tounes",
    stats: {
      pana: { left: 20, neutral: 20, right: 60 },
      coop: { left: 80, neutral: 0, right: 20 },
      econ: { left: 25, neutral: 15, right: 60 },
      reli: { left: 5, neutral: 25, right: 70 },
      soci: { left: 5, neutral: 15, right: 80 },
      demo: { left: 85, neutral: 10, right: 5 },
      decent: { left: 40, neutral: 30, right: 30 },
    },
    weights: {
      pana: 1,
      coop: 2,
      econ: 3,
      reli: 2,
      soci: 2,
      demo: 3,
      decent: 1,
    },
  },
  {
    name: "Parti des Travailleurs",
    stats: {
      pana: { left: 40, neutral: 20, right: 40 },
      coop: { left: 40, neutral: 20, right: 40 },
      econ: { left: 85, neutral: 10, right: 0 },
      reli: { left: 5, neutral: 5, right: 90 },
      soci: { left: 5, neutral: 10, right: 85 },
      demo: { left: 50, neutral: 30, right: 20 },
      decent: { left: 35, neutral: 30, right: 35 },
    },
    weights: {
      pana: 1,
      coop: 1,
      econ: 3,
      reli: 3,
      soci: 3,
      demo: 2,
      decent: 1,
    },
  },
  {
    name: "Coalition Al Karama",
    stats: {
      pana: { left: 70, neutral: 20, right: 10 },
      coop: { left: 25, neutral: 10, right: 65 },
      econ: { left: 40, neutral: 20, right: 40 },
      reli: { left: 95, neutral: 5, right: 0 },
      soci: { left: 95, neutral: 5, right: 0 },
      demo: { left: 20, neutral: 10, right: 70 },
      decent: { left: 15, neutral: 15, right: 70 },
    },
    weights: {
      pana: 2,
      coop: 1,
      econ: 0.5,
      reli: 3,
      soci: 3,
      demo: 3,
      decent: 1,
    },
  },
  {
    name: "Courant Démocrate (Attayar)",
    stats: {
      pana: { left: 35, neutral: 10, right: 55 },
      coop: { left: 75, neutral: 20, right: 5 },
      econ: { left: 70, neutral: 5, right: 25 },
      reli: { left: 15, neutral: 25, right: 60 },
      soci: { left: 20, neutral: 30, right: 50 },
      demo: { left: 70, neutral: 10, right: 20 },
      decent: { left: 55, neutral: 10, right: 35 },
    },
    weights: {
      pana: 1,
      coop: 2,
      econ: 3,
      reli: 2,
      soci: 2,
      demo: 3,
      decent: 1,
    },
  },
  {
    name: "Parti Baath Tunisien",
    stats: {
      pana: { left: 95, neutral: 5, right: 0 },
      coop: { left: 20, neutral: 5, right: 75 },
      econ: { left: 70, neutral: 20, right: 10 },
      reli: { left: 15, neutral: 20, right: 65 },
      soci: { left: 60, neutral: 20, right: 20 },
      demo: { left: 5, neutral: 10, right: 85 },
      decent: { left: 5, neutral: 5, right: 90 },
    },
    weights: {
      pana: 3,
      coop: 2,
      econ: 1,
      reli: 1,
      soci: 1,
      demo: 3,
      decent: 2,
    },
  },
  {
    name: "Ettakatol (FDTL)",
    stats: {
      pana: { left: 25, neutral: 45, right: 30 },
      coop: { left: 70, neutral: 5, right: 25 },
      econ: { left: 45, neutral: 10, right: 45 },
      reli: { left: 10, neutral: 20, right: 70 },
      soci: { left: 25, neutral: 15, right: 60 },
      demo: { left: 85, neutral: 10, right: 5 },
      decent: { left: 40, neutral: 30, right: 30 },
    },
    weights: {
      pana: 1,
      coop: 2,
      econ: 2,
      reli: 3,
      soci: 2,
      demo: 3,
      decent: 1,
    },
  },
  {
    name: "Al Joumhouri",
    stats: {
      pana: { left: 20, neutral: 50, right: 30 },
      coop: { left: 60, neutral: 10, right: 30 },
      econ: { left: 30, neutral: 10, right: 55 },
      reli: { left: 15, neutral: 25, right: 60 },
      soci: { left: 25, neutral: 35, right: 40 },
      demo: { left: 70, neutral: 15, right: 15 },
      decent: { left: 55, neutral: 25, right: 20 },
    },
    weights: {
      pana: 1,
      coop: 1,
      econ: 2,
      reli: 2,
      soci: 2,
      demo: 3,
      decent: 1,
    },
  },
];
